identifiers:
  "turista": 77818
  "educacao": 77819
  "saude": 77820
  "pesquisa": 77821
  "mulheres_economia_ativa": 77822
  "pib_pre_capita": 77823
  "idade_economia_ativa": 77824
  "exportacao": 77825
  "importacao": 77826
  "pib": 77827
  "espectativa_vida": 77830
  "idh": 77831
  "agua_potavel": 77832
  "rede_sanitaria": 77833
  "nivel_ensino": 77835
  "alfabetizacao": 77836
  "cultivo": 77838
  "pastagem": 77839
  "gas_natual": 77841
  "petroleo": 77842
  "densidade_demografico": 77844
  "homens": 77845
  "mulheres": 77846
  "area_rural": 77847
  "area_urbana": 77848
  "populacao": 77849
  "mortalidade": 77850
  "natalidade": 77851
  "crescimento_populaciov=nal": 77852
  "telefonia_celular": 77854
  "telefonia_fixa": 78855
  "internet": 77857
  "consumo_calorico": 77829
  "subnutricao": 77834

url: "https://servicodados.ibge.gov.br/api/v1/paises/BR/indicadores/"
